### PR TITLE
* Adding Option to Ignore Stop Words (English) from Tag Cloud

### PR DESCRIPTION
**Pull request by ankit-singhaniya**
Hi,
@chrismattmann

With this request, I am proposing a **Feature Addition** into existing **Tag Cloud Panel** of Banana.
### Option to Ignore Stop Words

**Description**: The Tag Cloud panel is typically to be used with a field with **only** Keywords, this assumes that the **Solr Field** does not contain **English Stop Words**. Even if they did, the count of stop words will surely be prevalent than other keywords to be visualized. Problem with this is when this assumption is invalid on some field of solr index this panel is used on, it results in a **Tag Cloud of Stop Words**
**Solution**: Use of a **List of Stop Words** in English to reject words to be included in the cloud.
**Approach**: Adding an Option in Panel Settings to be Enabled to Ignore Stop Words from the Solr Field. This way, both the configurations of the panel could be used.

original tag cloud
_Fig. 1: Original Tag Cloud Panel (and Output on some data)_

modified tag cloud
_Fig. 2: Modified Tag Cloud Panel (rejecting Stop Words)_

original tag cloud settings panel
_Fig. 3: Original Settings Page for Tag Cloud Panel_

modified tag cloud settings panel
_Fig. 4: Modified Settings Page for Tag Cloud Panel (adding a check-box for Stop Words)_

### CODE REVIEW

**Comment by chrismattmann** [comment]
awesome work @ankit-singhaniya ! Guys if you need any help getting this in let me know!

**Comment by chrismattmann** [comment]
ping @dougmcclure can someone take a look at this?

**Comment by chrismattmann** [comment]
ping @dougmcclure can you take a look?

**Comment by chrismattmann** [comment]
ping can someone take a look at this? @athana

**Comment by athana** [comment]
@chrismattmann @ankit-singhaniya  Ok, I merged it to `develop` branch. Thanks for your contribution!

**Comment by chrismattmann** [comment]
thank you @athana !

**Comment by ankit-singhaniya** [comment]
thank you @chrismattmann for bringing this up, and thanks @athana for taking look at the contribution!

**Pull request closed without merging**
