### PR TITLE
Added better map support to filter with geo-points (lat,lon)

### PR DESCRIPTION
**Pull request by karimfikry**
Please review the changes and merge them to the origin

### CODE REVIEW

**Comment by athana** [comment]
Kareem, do you want to merge the commits from 'develop' into 'release'? Or did you make a mistake in creating this pull request? I don't see you have any new modifications in this commit (except your previous commit from the last pull request). Before merging into release, we will have to wait until next week and do more testing.

**Comment by karimfikry** [comment]
Maybe some mistake happened. Let me check that again on Sunday and I'll send an email with the status I reached.

**Comment by karimfikry** [comment]
I think that's my latest commit:
https://github.com/LucidWorks/banana/commit/efb6939209e89b8b7bd7b98a963c66897737a960

But, seems that this commit joined yours somehow. If you can check this, it would be great. Anyways I'll check the commits again on Sunday and send an email to you.

**Comment by karimfikry** [comment]
I checked this now. I think it was mistake and I requested to merge develop into release. You can discard this for now. I checked my code in develop branch and It's the latest.

**Comment by athana** [comment]
Ok thanks. I will merge efb6939 into develop and test it. I will close this pull request now.

**Pull request closed without merging**
