### PR TITLE
World map

### PR DESCRIPTION
**Pull request by ankit-singhaniya**
Hi,
@chrismattmann

I am proposing the following **two** modifications (**Feature Addition**) to the existing **Map Panel** in Banana.
### Adding Antarctica to the World Map.

**Description**: The jVectorMap of **"world"** in Banana does not have the **Antarctic region**. Reason might be that the jVectorMap of the world only plots countries. But Antarctica as an Continent can add value to the existing world map for Data Visualization in Banana.
**Approach**: Linearly scaled jVectorMap Coordinates for Antarctica (standards) to target map size.

original map panel
_Fig. 1: Original Map Panel_

modified world map added antarctica
_Fig. 2: Modified Panel With Antarctica Region_
### Adding Capability of Finding Country by Country Names

**Description**: The Map panel by **default** needs a **solr field** that has Country Codes (**US, IN, etc**) and thus this makes it _**difficult to use_\* the panel on any other fields of indexed text.*
One problem in using it in normal text is that few codes are frequently found English text like "IN" meaning "inside" and not "India".
**Solution**: **(Optional) choice** to use Country Names than using Country Codes (default) for Finding Countries in the Solr Field.
**Approach**: _Maps Country Names_ given the list of Countries on the World Map _to corresponding Codes_ (that jVectorMap uses to plot).

modified panel option visible for world map selection
_Fig 1: Modified Panel Settings Page Showing Option to use Country Names for "World Map"_

modified panel option hidden for europe other than world map selection
_Fig. 2: Modified Panel Settings Page Hiding the Option of using Country Names for any other map than "World" Map_

original world map panel settings
_Fig. 3: Original Panel Settings Page_

### CODE REVIEW

**Comment by chrismattmann** [comment]
very cool we need this on my NSF Polar CyberInfrastructure work thanks @ankit-singhaniya !

**Comment by chrismattmann** [comment]
ping, can someone take a look at this? It's preventing me from using Banana in my polar work for the NSF.

**Comment by chrismattmann** [comment]
thanks to my USC students for these contributions.

**Comment by athana** [comment]
Thanks @ankit-singhaniya for your contributions! I'm truly appreciated. @chrismattmann I'm sorry for the delay. I will work on merging these contributions into the develop branch first, so you can try it while waiting for the next Banana release.

**Comment by chrismattmann** [comment]
thanks @athana really appreciate it man! we really like Banana and the work you've all been doing is fantastic. Keep it up. I'll keep teaching it in my CS572 Search Engines graduate course at USC :) http://sunset.usc.edu/classes/cs572_2015/

**Comment by athana** [comment]
@ankit-singhaniya @chrismattmann  there's a bug in this PR. When I used the "Country Names" mode in the world map, and then I clicked on a country (for example, Canada) to add a filter. It does not work properly because the filter value will be the country code value (CA for Canada), instead of the full country name. I will have to fix this before I merge it to `develop` branch.

**Comment by chrismattmann** [comment]
thanks @athana good catch. Do you need me/us to update, or do you got this one?

**Comment by athana** [comment]
@chrismattmann  I got this one. thanks.

**Comment by athana** [comment]
@chrismattmann @ankit-singhaniya  I fixed the bug and modified a few things. I separated the world maps into two maps: the original world map and the world-antarctica map. You guys can check it out in the `develop` branch (commit 6d07515bfeb92e6f102624c822429f4b8c5e787d)

**Comment by chrismattmann** [comment]
awesome job @athana  thank you so much! great job @ankit-singhaniya !

**Comment by ankit-singhaniya** [comment]
Thanks @athana for the quick fix, thanks @chrismattmann for following this
up. I am happy to have contributed this.

**Pull request closed without merging**
