### PR TITLE
Accessibility (Section 508) Enhancements

### PR DESCRIPTION
**Pull request by nickvasilyev**
The statement was not properly evaluated if  $routeParams.server was null.

### CODE REVIEW

**Comment by nickvasilyev** [comment]
Hey guys, any updates on this?

**Comment by aadel** [comment]
Looks fine! However, the inline styles were removed as they conflict with the dark theme (icons hardly seen). The styles need to be separately added to light and dark style sheets.

**Comment by nickvasilyev** [comment]
Got it, thanks. 

I am planning several more changes to some panels that I will submit this week.

**Comment by athana** [comment]
@aadel @nickvasilyev  Thanks!

**Pull request merged**
