### PR TITLE
add no-sanitized html mode

### PR DESCRIPTION
**Pull request by Joongho**
add no-sanitized html mode using 'ng-bind-html-unsafe'

### CODE REVIEW

**Comment by aadel** [comment]
thanks @Joongho for this however `ng-bind-html-unsafe` is deprecated since Angular 1.2. I think the correct way is to call `$sce.trustAs` instead of the above attribute. I'm also interested to know the use case behind this PR.

**Comment by Joongho** [comment]
Sorry for late reply.

The case I used was because of CSS for laying out images.

Here is what I did.

< style type="text/css">
#menu ul{  list-style: none; display:inline-flex;}
#menu li{ padding-right: 20px; display:inline-block; }
#menu img{ height:140px; width: 230px; }
< /style>
< div id="menu">< ul>
< li> < div> \* Summary < /div>
< a href="#/daxxxxx" target="_blank">< img src="./img/xxxxx.png"/></a></li>
.......
< /ul></div>

PS. 
I put whitespace because  I don't know how to write html code here.

Thanks.

**Comment by aadel** [comment]
@Joongho the use case is interesting but:
- Please squash your commits into a single one using `git rebase HEAD~2`.
- Check markdown guiedlines for how to insert code [here](https://guides.github.com/features/mastering-markdown/)
- `ng-bind-html-unsafe` does not work with Angular > 1.2

**Comment by Joongho** [comment]
I created anther one for this
https://github.com/LucidWorks/banana/pull/235

**Pull request closed without merging**
