### PR TITLE
Publish Banana WAR to Maven Central #201

### PR DESCRIPTION
**Pull request by lewismc**
Hi Folks
This PR addresses the desire and requirement to publish Banana .war artifact to Maven Central via OSSRH. I've added documentation to the README to detail how this can easily be factored into the existing release procedure.
I would be very keen to hear any feedback on the PR and happy to make changes to suit any feedback.
Thanks

### CODE REVIEW

**Comment by chrismattmann** [comment]
+1 from me

**Comment by lewismc** [comment]
Hi folks. Probably a decent time to follow this one back up.
Is there any desire to make this initiative part of the Banana release workflow?

**Comment by chrismattmann** [comment]
+1

**Comment by chrismattmann** [comment]
ping?

**Comment by lewismc** [comment]
Is there anything I can do here to get a code review on this PR? Thank you again folks @zimbatm @mwmitchell @davidfmiller @marceldegraaf

**Comment by athana** [comment]
@lewismc Thanks for your contribution. I merged it into `develop` branch. @chrismattmann

**Comment by lewismc** [comment]
@athana fantastic Sir. if you guys have any trouble at all with this then please ping me. Thank you Sir. Would be great to see the .war published to Maven Central more frequently now.

**Comment by marceldegraaf** [comment]
I'm sorry, but I think you tagged the wrong Marcel de Graaf :-).

**Comment by lewismc** [comment]
Sorry Marcel!

On Friday, December 4, 2015, Marcel de Graaf notifications@github.com
wrote:

> I'm sorry, but I think you tagged the wrong Marcel de Graaf :-).
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/LucidWorks/banana/pull/203#issuecomment-161926829.

## 

_Lewis_

**Comment by chrismattmann** [comment]
thanks @athana @lewismc !

**Pull request closed without merging**
