### PR TITLE
Allow human-friendly translations for facet fields to be defined on a per-dashboard basis

### PR DESCRIPTION
**Pull request by davidfmiller**

### CODE REVIEW

**Comment by davidfmiller** [comment]
A fix for this issue: https://github.com/LucidWorks/banana/issues/207

**Comment by davidfmiller** [comment]
Example modification to dashboard config file in order for the lang keys to be supported:

```
{
    ...
    "solr": { ... },
    "group": "Default",
    "lang" : {
        "facet.leadGroup" : "Lead Group",
        "facet.syndicationPartner" : "Syndication Partner",
        "facet.trackingReferringUrl" : "Referring URL",
        "facet.leadType" : "Lead Type",
        "facet.leadCategory" : "Lead Category"
    }
}
```

screen shot 2015-06-17 at 10 52 19 am

**Comment by aadel** [comment]
@davidfmiller very nice! I have two additions though:
- there are some places where human friendly names can be used, such as Table field list, FTS.
- it would be nice to have a more user friendly dashboard-wide setting to define the pairs, something like a new tab to "Dashboard Settings".

**Comment by davidfmiller** [comment]
I'll add the translation to the Table & FTS panels and update the PR.

Creating Dashboard setting/administration is a good idea, I'll put that on my todo list and start digging into it as time allows!

**Comment by davidfmiller** [comment]
Updated! Let me know what you think, thanks.

**Comment by aadel** [comment]
Looks good! Fixed an issue in FTS (aa3efdf7484b6a33780776c227842d18a3490a0c) and merged.

**Comment by davidfmiller** [comment]
Derp! Thanks,

**Pull request merged**
