### PR TITLE
solrcloud functionality for better load balancing (continued from #157)

### PR DESCRIPTION
**Pull request by harspras**
With regard to pull request #157 I have moved the changes from branch develop to dev-2.0. I have added few more changes in this pull request:
1. Added a patch and a README for enabling JSONP in zookeeper rest server to bypass Cross Origin issue. 
2. Updated the html code in accordance to dev-2.0 branch.
3. Bug fixes

### CODE REVIEW

**Comment by aadel** [comment]
Looks very good. But I wonder what's the advantage of using ZK-REST API over the built-in `/zookeeper` handler? I've noticed that sometimes clusterstate.json specifically does not reflect the state (blank dataUtf8), on Solr 5.0 and ZK 3.4.6. Other than that, looks pretty good.

**Comment by harspras** [comment]
The advantage of ZK-REST API over the built in /zookeeper handler is the continuous availability of solr node. Since most of the load and most of the request will be taken care by the solr node, if the solr node is not available, then the dashboard stops working. Also, if you plan on sharing your dashboard with someone else, then the other person should also have the knowledge of solr cluster, if anything goes wrong . To prevent all this I though of using ZK-REST Api. 

Regarding, your concern with clusterstate.json, I have the same concern too. I was thinking if it would be a better idea to use live_nodes instead of clusterstate.json. What do you think?

**Comment by aadel** [comment]
+1 for the reason behind depending on ZK-REST over the built-in handler and agree on using another approach to retrieve cluster state. But I think `collections` holds the respective states not `live_nodes`?

**Comment by harspras** [comment]
@aadel The collections node in Zookeeper holds the leader information only. Other than that most of the information is in the clusterstate.json. What is your opinion in this regard? Should I use clusterstate node and as a failover check the collections node?

**Comment by aadel** [comment]
Agree. It seems weird to me that sometimes `clusterstate.json` node does not reflect the actual state while respective `collections` states do. Have you encountered this issue at your end?

**Comment by aadel** [comment]
Actually, `collections` node holds all information not just leader but we have to iterate over all collections to gather required information. In the meantime, `clusterstate.json` should not be used with Solr 5 upwards. So, a better strategy could be to retrieve `live_nodes` through ZK API then query the state from a random live node using [Collections API](https://cwiki.apache.org/confluence/display/solr/Collections+API). What do you think?

**Comment by harspras** [comment]
I have not yet faced issue with `clusterstate.json` as of yet. I know that it might not always represent correctly the current state of the cluster but nothing very serious. 

In your first comment above, you said that you find blank `datautf8` when using zookeeper 3.4.6. Was it while using ZK-REST API or in general? 

Also, if `clusterstate.json` is definitely a problem with Solr 5 then there is no other option but to use either the `collections` or `live_nodes` nodes. 

Let me see if there is a serious problem with `clusterstate.json`. Also I will try to use live_nodes or Collections API to get a working node.

**Comment by harspras** [comment]
@aadel I have been looking at this problem you mentioned and I think, we can work this out by two requests, instead of one. As collections node does not have `status.json` in 4.x I can lookup a live node from live_nodes and try using the CollectionsAPI to get correct cluster status. If for some reason, the selected node is down or is not able to respond to the cluster status query, I will select another node and try again. This method will increase the number of requests required but might be able to tackle `clusterstate.json` issue in Solr 5.x

**Comment by aadel** [comment]
@harspras agree on this strategy. It will increase the number of requests but, as you mentioned, will tackle `clusterstate.json` issue in Solr 5.x. I was also thinking of the reverse, i.e. query Collections API using te current node, and if it happens to be unavailable, send ZK query and set a live node instead.

**Comment by harspras** [comment]
@aadel made changes according to your last comment. will use the current solr node first and if it does not work, i will fetch live_node list from ZK REST API and then use those nodes to get cluster status.

**Comment by harspras** [comment]
@aadel Any progress on this issue?

**Comment by shalinmangar** [comment]
Hello,

I am one of the committers on Apache Solr and I have a few concerns about this solution.

The way cluster state is managed in Solr has been changed in 5.0. Any collection created by Solr 5.0 and beyond gets it's own cluster state node which is kept in /collections/[collection_name]/state.json so reading the /clusterstate.json is no longer sufficient. If you want cluster state information then there is a 'clusterstatus' API which can give you all the information you need e.g. "http://localhost:8983/solr/admin/collections?action=clusterstatus&wt=json"

Please do not use the ZK API directly. Tomorrow we may again change the way the state is maintained in ZK and you will have to change banana again. Can you explain what problem are you trying to solve and maybe I can provide an alternative solution?

**Comment by aadel** [comment]
Hello @shalinmangar what we are trying to determine is to which node should the Collections API request go. The current approach is we get live_nodes from ZK API and select random live node to send the request to. Of course, a more reliable approach is welcome.

**Comment by harspras** [comment]
Hi Shalin,

Earlier I was using the state maintained in the Zookeeper Node, but as Adel pointed out earlier, Solr 5.0 has a different approach, I am now using Collections API only to get the desired status. The ZK API will only be used to get a live node in case the solr node present in settings is down.

**Comment by harspras** [comment]
@aadel Any updates on this?

**Comment by aadel** [comment]
@harspras I think we are in a good state for merge as the feature code no longer depends on `clusterstate.json`. Thanks for the cool feature!

**Comment by harspras** [comment]
@aadel Wow! Thank you so much.

**Pull request merged**
